# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  github-release: haskell-works/github-release@1.3.3
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
        - attach_workspace:
            at: ~/repo
        - checkout
        - attach_workspace:
            at: ~/repo/gateway_nfv_plugin
        - run:
            name: Build gateway_nfv_scheduler:${CIRCLE_TAG} image
            command: docker build -t gateway_nfv_scheduler:${CIRCLE_TAG} .
        - run:
            name: Export gateway_nfv_scheduler:${CIRCLE_TAG} image
            command: docker save -o gateway_nfv_scheduler_${CIRCLE_TAG}.tar gateway_nfv_scheduler:${CIRCLE_TAG}
        - run:
            name: Create a tarball
            command: tar -czvf gateway_nfv_scheduler_${CIRCLE_TAG}.tar.gz gateway_nfv_scheduler_${CIRCLE_TAG}.tar
        - persist_to_workspace:
            root: .
            paths:
              - gateway_nfv_scheduler_${CIRCLE_TAG}.tar.gz
        - store_artifacts:
            path: gateway_nfv_scheduler_${CIRCLE_TAG}.tar.gz
  release:
    executor: github-release/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Compute version number
          command: |
            echo "Release ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}"
      - github-release/release:
          tag: ${CIRCLE_TAG}
          title: ${CIRCLE_PROJECT_REPONAME}
          artefacts-folder: .
workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - build
          context: github
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
        
