# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
        - attach_workspace:
            at: ~/repo
        - checkout
        - setup_remote_docker
        - attach_workspace:
            at: ~/repo/gateway_nfv_plugin
        - run:
            name: Build gateway_nfv_scheduler:${CIRCLE_BRANCH} image
            command: |
              ls -la 
              docker build -t gateway_nfv_scheduler:${CIRCLE_BRANCH} .
        - run:
            name: Export gateway_nfv_scheduler:${CIRCLE_BRANCH} image
            command: |
              docker save -o gateway_nfv_scheduler_${CIRCLE_BRANCH}.tar gateway_nfv_scheduler:${CIRCLE_BRANCH}
              ls -la
        - run:
            name: Create a tar.gz file
            command: |
              echo "Package gateway_nfv_scheduler_${CIRCLE_BRANCH}.tar.gz"
              ls -la ~/repo
              mkdir -p ~/repo/artifacts
              tar -czvf gateway_nfv_scheduler_${CIRCLE_BRANCH}.tar.gz gateway_nfv_scheduler_${CIRCLE_BRANCH}.tar
              ls -la 
              ls -la ~/repo
              cp -rf gateway_nfv_scheduler_${CIRCLE_BRANCH}.tar.gz ~/repo/artifacts
              ls -la ~/repo/artifacts
        - persist_to_workspace:
            root: ~/repo
            paths:
              - artifacts
  release:
    docker:
    - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Compute version number
          command: |
            echo "Release ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}"
            ls -la ~/repo/
            ls -la ~/repo/artifacts
            # go get github.com/tcnksm/ghr
            # ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_BRANCH} ~/repo/artifacts/
workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              only: circleci-project-setup
      - release:
          requires:
            - build
          filters:
            branches:
              only: circleci-project-setup
        
