#! /bin/sh
### BEGIN INIT INFO
# Provides:          statisticcollection
# Required-Start:    $local_fs $network $time $remote_fs
# Required-Stop:     $local_fs $network $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starting statistic collection scheduler daemon
# Description:       Starting statistic collection scheduler, a daemon process
### END INIT INFO#

set -e

DAEMONAPP_OPTS="/statistics_collection/statistic_collection_run.py"

# stop statisticcollection before changing its PID file!
PIDFILE="/var/run/statcol.pid"

DAEMONAPP="/usr/bin/python3.6"
NAME="python3.6"

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
test -f $DAEMONAPP || exit 0

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

create_pidfiledir() {
    if [ ! -d /var/run/statcol ]
    then
        mkdir -p /var/run/statcol
    fi
}

DAEMONAPP_start() {
    log_daemon_msg "Starting statistic collection" "$NAME"
    create_pidfiledir
    start-stop-daemon --start --background -m --oknodo --exec "$DAEMONAPP" $DAEMONAPP_OPTS \
                      --pidfile "$PIDFILE"
    # log_end_msg "Statistic collection is started" "$NAME"
}

DAEMONAPP_stop() {
    log_daemon_msg "Stopping statistic collection" "$NAME"
    start-stop-daemon --stop --quiet --oknodo --name "$NAME" --retry 3 \
                      --pidfile "$PIDFILE"
    # log_end_msg "Statistic collection is stopped" "$NAME"
}

case "$1" in
  start)
    DAEMONAPP_start
    ;;
  stop)
    DAEMONAPP_stop
    ;;
  reload|force-reload)
    DAEMONAPP_stop
    DAEMONAPP_start
    ;;
  restart)
    DAEMONAPP_stop
    DAEMONAPP_start
    ;;
  status)
    status_of_proc "$DAEMONAPP" "$NAME" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0

